# Step 1: Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Step 2: Set the working directory inside the container
WORKDIR /usr/src/app

# Step 3: Copy the package.json and package-lock.json files
COPY package*.json ./

# Step 4: Install the app dependencies
RUN npm install

# Step 5: Copy the rest of the application source code
COPY . .

# add uri
ENV MONGODB_URI=""

# Step 6: Expose the required ports (3000 for Express and Socket.io, 3001 for PeerJS)
EXPOSE 3000
EXPOSE 3001

# Step 7: Define the command to start both servers
CMD ["node", "server.js"]
