FROM node:18-alpine AS build

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/text-video-chat-frontend /usr/share/nginx/html

EXPOSE 80

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]